source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DoSomeThings_Example', :exclusive => true do
  pod 'DoSomeThings', :path => '../'
end

target 'DoSomeThings_Tests', :exclusive => true do
  pod 'DoSomeThings', :path => '../'

  
end
